server:
  host: "0.0.0.0"
  port: 8000
  hot_reload: true 
  log_level: "INFO" 

schemas:
  import_path: "some path"
  models:
    User: "app.schemas.users.User" 
    UserNotFound: "app.schemas.users.NotFound"

endpoints:
  - group: "user"
    version: "v1"
    base_path: "/users"

    routes:
      - path: "/"
        method: "GET"
        description: "Fetch all users"
        handler: "handlers.user.get_users"
        response:
          200:
            model: None
            description: "Successfull" 
          404:
            model: None 
            description: "Failed" 

      - path: "/{user_id}"
        method: "GET"
        description: "Get details of specific user"
        handler: "some handler"
        response:
          200:
            model: User
          404:
            model: UserNotFound